version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.12.2
  aws-ecs: circleci/aws-ecs@01.3.0

jobs:
  infrastructure-providing-and-deploy:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Terraform init
          command: |
            cd IAC &&
            terraform init
      - run:
          name: Terraform provide and deploy
          command: |
            cd IAC &&
            PROJECT_REPONAME=$(echo $CIRCLE_PROJECT_REPONAME | tr '[:upper:]' '[:lower:]') &&
            terraform apply -auto-approve -var="ecr_image_tag=${CIRCLE_SHA1}" -var="repository_name=${PROJECT_REPONAME}"

workflows:
  main:
    jobs:
      - aws-ecr/build-and-push-image:
          context: TerraformContext
          repo: "${CIRCLE_PROJECT_REPONAME,,}"
          tag: "${CIRCLE_SHA1}"
          create-repo: true
          aws-access-key-id: TF_VAR_aws_provider_key
          aws-secret-access-key: TF_VAR_aws_provider_secret
          account-url: TF_VAR_aws_ecr_account_url
          filters:
            branches:
              only:
                - master
                - qa
      - infrastructure-providing-and-deploy:
          context: 
            - TerraformContext
            - ElasticContext
          requires:
            - aws-ecr/build-and-push-image
